### ISSUE TITLE
Scrollbars show up although they shouldn't

### ISSUE THREAD

**Issue by qortex** [creativetimofficial/ct-paper-dashboard-2-pro#1]
Scrollbars appear although they shouldn't on Firefox (v62.0.2 (64-bit)). See screenshots attached.

It looks like it doesn't appear on Paper Dashboard v1.

![screenshot from 2018-10-03 09-50-58](https://user-images.githubusercontent.com/37897072/46398078-64303180-c6f4-11e8-973e-1c95297342d3.png)
![screenshot from 2018-10-03 09-51-21](https://user-images.githubusercontent.com/37897072/46398079-64303180-c6f4-11e8-820d-bc98e11f56a0.png)

**Comment by qortex** [comment]
@alexandru-paduraru

**Comment by qortex** [comment]
Workaround for sidebar:
```
.sidebar-wrapper {
  overflow-x: hidden !important;
}
```
But that doesn't work for the other controls as they might actually need the scrollbars.

**Comment by qortex** [comment]
@alexandru-paduraru  , where can I find some help? Thanks

**Comment by alexandru-paduraru** [comment]
@CortexMic sorry for the late response, my colleague @groovemen will have a look and give you a solution soon :D

**Comment by qortex** [comment]
@alexandru-paduraru 
Well... didn't quite happen yet!
Any timeframe for an answer?
Thanks

**Comment by groovemen** [comment]
Hello @CortexMic, 
Thank you for using our products and sorry for the waiting time, I checked on the latest version of Firefox (v62.0.3 (64-bit) on IOS) and everything is looking good on the same pages that you have shown us. Please let us know about your machine operating system; also check the images attached below:

<img width="1440" alt="screenshot 2018-10-16 at 15 44 42" src="https://user-images.githubusercontent.com/21063398/47020789-cceec380-d162-11e8-8112-d2f1667a5edf.png">

<img width="1437" alt="screenshot 2018-10-16 at 15 38 54" src="https://user-images.githubusercontent.com/21063398/47020577-5782f300-d162-11e8-984f-8ba40c76960b.png">

All the best, 
Stefan

**Comment by qortex** [comment]
Weird, I still see scrollbars on my Firefox 62.0.3 (64-bit) Fedora. But also Windows. I'll take some time to do a benchmark through the various platforms I have, trying to narrow down what might cause that.

Thanks for looking into that,
Michael
