### ISSUE TITLE
Css style should use sass variable in .main-panel but uses magic constant instead

### ISSUE THREAD

**Issue by qortex** [creativetimofficial/ct-paper-dashboard-2-pro#2]
In _sidebar-and-main-panel.scss line 438, code is:
```
.main-panel{
    [...]
    background-color: #f4f3ef;
```

And should be:
```
.main-panel{
    [...]
    background-color: $default-body-bg;
```

**Comment by groovemen** [comment]
Hello @CortexMic, 

thank you for using our products and for your suggestion. We will fix this and integrate into the next update. Sorry for the inconvenience. 

All the best, 
Stefan
