### ISSUE TITLE
Sidebar is brown by default, whereas should be "default color"

### ISSUE THREAD

**Issue by qortex** [creativetimofficial/ct-paper-dashboard-2-pro#4]
In _sidebar-and-main-panel.scss
```
&[data-color="brown"]{
      @include sidebar-color($default-color);
    }
```
should be
```
&[data-color="default"]{
      @include sidebar-color($default-color);
    }
```
and the corresponding html should be `data-color="default"`, because "brown" does not make sense when you style the template to another color.

**Comment by groovemen** [comment]
Hello @CortexMic,
Thank you for using our products, we will consider your suggestion and we'll try to integrate it into the next update. 

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
